### PR TITLE
jidea-191 Add small delay to parameter option tooltips

### PR DESCRIPTION
**Pull request by david-mears-2**
This is to make it slightly less visually chaotic when quickly mousing through different options - avoids obscuring options when you are trying to select them

### CODE REVIEW

**Comment by david-mears-2** [comment]
Please review at your leisure!

**Comment by EmmaLRussell** [comment]
Added a ticket for this: https://mrc-ide.myjetbrains.com/youtrack/issue/JIDEA-191/Add-delay-to-parameter-option-tooltips

**Review by EmmaLRussell — APPROVED** [review]
It's annoying that the None option is getting placed on the right since the tooltip width was increased. Could slim it down to fit it above again to avoid the obscuring problem? But this is fine too. 

Could you align the package version numbers before merging please?

**Comment by david-mears-2** [comment]
> It's annoying that the None option is getting placed on the right since the tooltip width was increased. Could slim it down to fit it above again to avoid the obscuring problem? But this is fine too.

I agree. But I think making all tooltips narrow enough to prevent this (175px) results in them being too narrow and that's worse overall.

**Pull request merged**
